PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX td: <https://www.w3.org/2019/wot/td#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#>
    {
        ?wheat a was:Crop, was:Wheat;
        		td:title "crop: wheat.";
         	was:idealMoistureLevel "120".

        ?corn a was:Crop, was:Corn;
        		td:title "crop: corn.";
         	was:idealMoistureLevel "80".
    }.
} WHERE {
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#crop-", strUUID())) AS ?wheat)
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#crop-", strUUID())) AS ?corn)
}