PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX td: <https://www.w3.org/2019/wot/td#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#>
    {
        ?SoilMoisture1 a was:SoilMoisture;
            td:title "Moisture Level of section 1";
	        td:hasBase <http://localhost:1080/api/soilMoisture/1/>;
            was:currentMoistureLevel "70".

        ?SoilMoisture2 a was:SoilMoisture;
            td:title "AMoisture Level of section 2";
	        td:hasBase <http://localhost:1080/api/soilMoisture/2/>;
            was:currentMoistureLevel "125".

        ?SoilMoisture3 a was:SoilMoisture;
            td:title "Moisture Level of section 3";
	        td:hasBase <http://localhost:1080/api/soilMoisture/3/>;
            was:currentMoistureLevel "70".

        ?SoilMoisture4 a was:SoilMoisture;
            td:title "Moisture Level of section 4";
	        td:hasBase <http://localhost:1080/api/soilMoisture/4/>;
            was:currentMoistureLevel "125".
    }.
} WHERE {
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#soilMoisture-", strUUID())) AS ?SoilMoisture1)
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#soilMoisture-", strUUID())) AS ?SoilMoisture2)
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#soilMoisture-", strUUID())) AS ?SoilMoisture3)
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#soilMoisture-", strUUID())) AS ?SoilMoisture4)
}