PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?td WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#> {
   bind (<PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#farm-4b56b29a-c113-47b0-ae5e-7065ed18c0d8> as ?farm)
   ?farm a was:Farm.    
   ?farm hmas:contains ?tractor.
   ?tractor a was:Tractor.
 }
}
> as ?farm)
   ?farm a was:Farm.
   ?tractor a was:Tractor. 
   ?tractor td:hasActionAffordance ?aff.
   ?tractor hmas:hasProfile ?td.
   ?aff a was:ReadSoilMoistureAffordance. 
 }
}
