PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?crop WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#section-f3e548d0-7498-4b47-bcd8-a86cb2085ea9> as ?section)
   ?section a was:Section.
   ?section was:grows ?crop.
 }
}