PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?idealMoistureLevel WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#crop-ef104eaf-2299-4a9f-a56b-1c3d4bbdd4da> as ?crop)
        ?crop a was:Crop.
        ?crop was:idealMoistureLevel ?idealMoistureLevel.
 }
}