PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?requiredMoistureLevel WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-gero#crop-cb8157e1-80d9-4f1d-8b33-150f38c67034> as ?crop)
        ?crop a was:Crop.
        ?crop was:idealMoistureLevel ?idealMoistureLevel.
 }
}